# Generated by Django 5.1.6 on 2025-03-02 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('wireframe', models.ImageField(upload_to='')),
                ('trello', models.URLField(blank=True, null=True)),
                ('case_study', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
